export const broadcasts = [
  null, // index 0 biar gampang, Dragon Ball mulai dari 1
  `--------------- Broadcast dragon ball 2 -------------------\n\nDari ufuk timur, berdirilah sebuah gedung megah, menatap langit dengan wibawa yang tak tergoyahkan.\nGerbangnya yang lebar seakan mengundang para penjelajah masuk ke dalam ruang terbesar,\ndi mana kursi terbanyak tersusun rapi, menunggu derap langkah dan gema suara yang akan mengguncang pikiran.\n\n✨ Di sanalah, seminar-seminar agung dan pertemuan besar pernah digelar,\nmenjadi altar bagi ide-ide yang mengubah arah peradaban.\nNamun jangan terbuai oleh kilau fasad modernnya—\nkarena di balik cahaya itu, ada jejak Paragon Corp yang menorehkan tanda pada tubuh bangunannya.\n\n🌑 Hati-hati… di ketinggian lantainya,\ndistorsi waktu berkelindan dengan anomali ruang,\nmenciptakan lorong misteri yang hanya bisa ditembus oleh jiwa yang teguh.\n\n🐉 Hanya dengan keberanianmu menafsirkan simbol dan langkah tegap menuju cahaya itulah,\nbola naga kedua akan menyingkap dirinya di hadapanmu.`,

  `--------------- Broadcast dragon ball 3 -------------------\n\nDi jantung pertemuan empat penjuru, berdirilah sebuah gedung vintage yang seakan menjadi saksi bisu perjalanan masa.\nIa dikelilingi oleh empat bangunan yang saling berseberangan, seolah menjaga rahasia lama yang terpatri di sana.\n\n🔹 Di balik pintu lantai keduanya yang khas dan istimewa, dekat dengan para penjaga himpunan,\ntersimpan kisah dua keluarga besar yang bernaung di bawah atap yang sama—\nmenyatukan perbedaan dalam satu rumah yang sederhana namun penuh makna.\n\n🪑 Namun, jangan tertipu oleh keanggunan sejarahnya,\nsebab di dalamnya, deretan kursi kayu sempit yang dibenci banyak jiwa menunggu dengan sabar,\nsebagai ujian kenyamanan dan ketahanan.\n\n🕌 Di bawahnya, sebuah ruang hening untuk bersujud menandai lapisan yang lebih dalam,\nmenjadi penyeimbang riuhnya percakapan dan rapat di atasnya.\n\n🐉 Carilah pintu itu, rasakan nafas sejarahnya,\ndan hanya mereka yang mampu membaca keseimbangan antara kenyamanan dan penderitaan,\nyang akan menemukan Dragon Ball ketiga di sana.`,

  `--------------- Broadcast dragon ball 4 -------------------\n\nDi antara tembok gagah sang penjaga mesin dan rancangan,\nterhampar sebuah teras terbuka—bukan ruang tertutup,\nmelainkan halaman ide dan percakapan yang tak pernah padam.\n\n🌞 Di atasnya, panel surya menatap langit,\nmenyerap cahaya matahari dan memantulkannya menjadi energi,\nseolah menghidupkan semangat para pencari ilmu yang bernaung di bawahnya.\n\n🪑 Bangku-bangku sederhana berjajar,\nmenjadi saksi bisu perdebatan, tawa, dan rencana masa depan.\nSementara itu, di sela-selanya tumbuh tanaman hias dan pohon kecil,\nmemberikan sejuk di tengah riuh inovasi.\n\n⚙️ Namun, jangan remehkan lantai di bawahnya—\nsebuah lapisan tersembunyi yang dapat bergerak, dikendalikan, dan berubah,\nibarat rahasia mesin raksasa yang menanti disentuh oleh tangan-tangan berani.\n\n🐉 Di sinilah gagasan bertemu kenyataan,\ndi sinilah energi berpadu dengan kreasi,\ndan hanya mereka yang peka membaca harmoni ruang terbuka ini\nakan mampu merasakan getaran Dragon Ball keempat.`,

  `--------------- Broadcast dragon ball 5 -------------------\n\nDi pusat samudra ilmu kampus ini berdiri sebuah bangunan megah,\nbertingkat-tingkat, berfasad modern, berjendela banyak\nyang memantulkan cahaya mentari ke segala arah,\nseolah menyeruput pengetahuan dari jagat raya.\n\nDi dalamnya terbentang ruang baca luas,\nsunyi namun sarat bisikan gagasan,\ndikelilingi rak buku menjulang bagai hutan pengetahuan\ndan mesin-mesin digital yang membuka gerbang data tak terbatas.\n\n💻 Di sudut tertentu, komputer katalog menunggu disentuh,\nsementara meja layanan berdiri tegak,\nmenjadi penjaga peralihan antara dunia nyata dan dunia literasi.\n\n🤫 Ada sebuah ruang unik di mana manusia berkumpul\nnamun tak boleh berucap—ruang diskusi tanpa suara,\ntempat ide berperang hanya lewat tatapan dan coretan pena.\n\nNamun, jangan terkecoh.\nDi lantai terbawah, sebuah kantin sederhana menjadi saksi—\nsebelum tawa mahasiswa berubah menjadi hening,\nsebelum derap langkah menuju \"pembantaian\" akademik dimulai. 🍽️\n\n🐉 Maka di sinilah Dragon Ball kelima bersemayam:\ndi tengah ribuan buku, layar digital, dan kesunyian yang khidmat,\nmenanti mereka yang berani menatap pengetahuan\nbukan hanya sebagai sumber jawaban,\ntetapi juga sebagai ujian jiwa.`,

  `--------------- Broadcast dragon ball 6 -------------------\n\nAda sebuah gedung bertingkat yang menjulang dengan fasad formal,\nsering menjadi panggung kata-kata berat,\ntempat seminar, sidang tesis, dan disertasi\nyang menentukan nasib para penimba ilmu. 🎓📜\n\nNamun, jangan salah.\nDi balik wibawanya, bersemayam rumor kelam—\nkisah lama tentang jiwa yang tak lagi kembali,\nmeninggalkan bayang-bayang muram\nyang hingga kini masih bergaung di lorong-lorongnya. 🕯️👤\n\nTempat ini juga menjadi arena kuliah tamu yang ramai,\npenuh tamu agung dan orasi intelektual.\nTetapi bagi sebagian,\ntempat ini tak lebih dari ruang sunyi dengan kisah rahasia,\nbahkan disebut-sebut sebagai toilet pribadi Seniro Bobi,\nironis, namun nyata. 🚻😅\n\n🐉 Maka, di balik keanggunan dan misteri kelamnya,\nDragon Ball keenam bersemayam,\nmenunggu mereka yang berani melangkah masuk,\nmenyibak aura akademik yang bercampur dengan bisikan masa lalu.`,

  `--------------- Broadcast dragon ball 7 -------------------\n\nEnam bola naga sudah kalian genggam,\nnamun pencarian belumlah tuntas.\nAda satu tempat terakhir—\nmahkota kebanggaan para pengendali daya. 🌩️\n\nIa berdiri gagah, menyimpan nama yang melekat erat\ndengan arus, tegangan, dan kekuatan bangsa.\nDi sanalah para penerus cahaya ditempa,\nmenjadi penjaga nyala negeri. 🔋✨\n\nBangunan ini tak sekadar dinding dan ruang,\nia adalah simbol kehormatan sebuah jurusan,\ntempat para ksatria listrik bernaung\ndan menatap masa depan dengan penuh kebanggaan. ⚡🏛️\n\nCarilah ia.\nKarena di sanalah Dragon Ball ketujuh menunggu—\ndan hanya mereka yang mengerti arti “daya”\nyang bisa menyentuhnya. 🐉🌟`
];
